# Generated by Django 5.0.7 on 2024-07-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='image',
        ),
    ]
