# Generated by Django 5.0.7 on 2024-07-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_remove_userdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='images',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
