# Generated by Django 5.0.7 on 2024-07-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_userdata_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='images',
            new_name='image',
        ),
    ]
