# Generated by Django 5.0.7 on 2024-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_rename_images_userdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
